os: osx
osx_image: xcode11
language: swift

install:
  - gem install cocoapods
  - pod install --repo-update

script:
  - set -o pipefail && xcodebuild -scheme Lotus -workspace Lotus.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.0' build test | xcpretty --color
after_success:
  - bash <(curl -s https://codecov.io/bash)
